# Rust基础： 返回值与错误处理

## `Option<T>`

```rust
fn main() {
    let x = Some(5);
    let y = None;

    match x {
        Some(i) => println!("i: {}", i),
        None => println!("None"),
    }

    match y {
        Some(i) => println!("i: {}", i),
        None => println!("None"),
    }

    let five = Some(5);
    let six = plus_one(five);
    let none = plus_one(None);

    println!("six: {:?}", six);
    println!("none: {:?}", none);

    // is_some is_none

    let a = Some(5);
    asset!(a.is_some());
    asset!(!a.is_none());
}

fn plus_one(x: Option<i32>) -> Option<i32> {
    match x {
        Some(i) => Some(i + 1),
        None => None,
    }
}

fn plus_one_0(x: Option<i32>) -> Option<i32> {
    x.map(|i| i + 1)
}

fn plus_one_1(x: Option<i32>) -> Option<i32> {
    Some(x? + 1)
}
```

## 错误处理

Rust 中的错误主要分为两类：

- **可恢复错误**，通常用于从系统全局角度来看可以接受的错误，例如处理用户的访问、操作等错误，这些错误只会影响某个用户自身的操作进程，而不会对系统的全局稳定性产生影响。

- **不可恢复错误**，刚好相反，该错误通常是全局性或者系统性的错误，例如数组越界访问、系统启动时发生了影响启动流程的错误等，这些错误的影响往往对于系统来说是致命的。

- `Result<T, E>` 用于可恢复错误
- `panic!` 用于不可恢复错误

## backtrace 栈展开

命令行中使用 `RUST_BACKTRACE=1` 可以打印出详细的错误栈信息。

```shell
RUST_BACKTRACE=1 cargo run
```

## `Result<T, E>`

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

### 使用 match

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => {
            eprintln!("Error: {:?}", error);
        }
    };
}
```

### 使用 `unwrap` 或 `expect`

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt").unwrap();

    let f = File::open("hello.txt").expect("Failed to open hello.txt");
}
```

### 使用 `Result<T, E>` 的 `map` 方法

```rust
use std::fs::File;

fn main() {
    let number = "42";
    let number = number.parse::<i32>().map(|i| i * 2);
    println!("number: {:?}", number);
}
```

### 使用 `Result<T, E>` 的 `map_err` 方法

```rust
use std::fs::File;

fn main() {
    let number = "42";
    let number = number.parse::<i32>().map_err(|e| e.to_string());
    println!("number: {:?}", number);
}
```

## 传播错误

使用 `?` 运算符传播错误。

不使用 `?` 运算符：

```rust
use std::fs::File;

fn main() -> std::io::Result<()> {
    let f = File::open("hello.txt");
    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();
    match f.read_to_string(&mut s) {
        Ok(_) => Ok(()),
        Err(e) => Err(e),
    }

    Ok(())
}
```

使用 `?` 运算符：

```rust
use std::fs::File;

fn main() -> std::io::Result<()> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(())
}
```

`?` 就相当于：

```rust
fn foo(result: Result<T, E1>) -> Result<T, E2> where
    E2: From<E1>
{
    match result {
        Ok(value) => value,
        Err(error) => return Err(E2::from(error)),
    }
}
```

## Option 与 Result 的转换

```rust
fn main() {
    let x = Some(5);
    let y = None;

    let x = x.ok_or("x is None");
    let y = y.ok_or_else(|| "y is None");

    println!("x: {:?}", x);
    println!("y: {:?}", y);

    let x = Ok::<i32, &str>(5);
    let y = Err::<i32, &str>("error");

    let x = x.ok();
    let y = y.ok();

    println!("x: {:?}", x);
    println!("y: {:?}", y);
}
```

## 课后习题

```rust
// 修复 call 函数的错误
// 当 b 为 None 时，按照默认值 1

fn call(a: i32, b: i32) -> Result<f64, String> {
    let r = divide(a, b).unwrap_or(1.0);
    let s = sqrt(r).map_err(|e| format!("{:?}", e))?;

    Ok(s) //;
}

fn divide(a: i32, b: i32) -> Option<f64> {
    if b != 0 {
        Some(a as f64 / b as f64)
    } else {
        None
    }
}

#[derive(Debug)]
pub enum MathError {
    DivisionByZero,
    NegativeSquareRoot,
}

fn sqrt(x: f64) -> Result<f64, MathError> {
    if x < 0.0 {
        Err(MathError::NegativeSquareRoot)
    } else {
        Ok(x.sqrt())
    }
}
```

